# Naive Bayes 실습

https://heung-bae-lee.github.io/2020/04/14/machine_learning_08/ 참고

# 1. Gaussian Naive Bayes

- 데이터, 모듈 불러오기

In [1]:
from sklearn import datasets

In [3]:
from sklearn.naive_bayes import GaussianNB #가우시안 나이브베이즈 

In [4]:
import pandas as pd

In [5]:
iris = datasets.load_iris()
df_X=pd.DataFrame(iris.data)
df_Y=pd.DataFrame(iris.target)

In [6]:
df_X.head() #설명변수-연속형

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [7]:
df_Y.head() #0,1,2 세개의 범주

0
0  0
1  0
2  0
3  0
4  0

- 모델 피팅

In [11]:
gnb = GaussianNB() #함수 가져오기
fitted = gnb.fit(iris.data, iris.target) #데이터 학습
y_pred = fitted.predict(iris.data) 

In [15]:
fitted.predict_proba(iris.data)[[1,2,3]] #1,2,3번 데이터의 각 범주별 확률

array([[1.00000000e+00, 1.51480769e-17, 2.34820051e-25],
       [1.00000000e+00, 1.07304179e-18, 2.34026774e-26],
       [1.00000000e+00, 1.46619543e-17, 2.95492722e-25]])

- Confusion matrix 구하기

In [16]:
from sklearn.metrics import confusion_matrix

In [17]:
confusion_matrix(iris.target,y_pred)

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  3, 47]], dtype=int64)

- Prior 설정하기:   
범주별 사전확률 설정해주기, 미리 결과에 대해 어느정도 비율로 간다는 것을 알고 있을 때 사용하는 옵션

In [19]:
gnb2 = GaussianNB(priors=[1/100,1/100,98/100])
fitted2 = gnb2.fit(iris.data, iris.target)
y_pred2 = fitted2.predict(iris.data)
confusion_matrix(iris.target, y_pred2)

array([[50,  0,  0],
       [ 0, 33, 17],
       [ 0,  0, 50]], dtype=int64)

In [20]:
gnb3 = GaussianNB(priors=[1/100,98/100,1/100])
fitted3 = gnb3.fit(iris.data, iris.target)
y_pred3 = fitted3.predict(iris.data)
confusion_matrix(iris.target, y_pred3)

array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0, 14, 36]], dtype=int64)

# 2. Multinomial naive bayes

- 모듈 불러오기 및 데이터 생성

In [21]:
from sklearn.naive_bayes import MultinomialNB

In [22]:
import numpy as np

In [23]:
X = np.random.randint(5, size=(6, 100))
y = np.array([1, 2, 3, 4, 5, 6])

In [24]:
X

array([[0, 2, 1, 1, 4, 4, 3, 0, 0, 4, 4, 4, 2, 2, 2, 3, 2, 3, 3, 1, 3, 4,
        4, 1, 1, 0, 4, 1, 2, 4, 0, 0, 4, 4, 4, 1, 3, 4, 2, 1, 1, 3, 0, 3,
        0, 3, 2, 0, 0, 2, 0, 0, 0, 2, 1, 4, 0, 3, 4, 2, 2, 2, 2, 2, 0, 3,
        4, 2, 3, 2, 4, 2, 1, 0, 0, 2, 3, 4, 4, 3, 0, 4, 1, 1, 3, 1, 2, 4,
        1, 3, 3, 4, 2, 2, 3, 3, 0, 0, 1, 4],
       [2, 4, 2, 2, 2, 3, 3, 4, 0, 1, 3, 0, 2, 0, 2, 4, 0, 4, 2, 3, 0, 3,
        0, 3, 1, 3, 2, 2, 4, 2, 1, 1, 3, 2, 3, 1, 3, 0, 4, 4, 4, 3, 4, 2,
        4, 4, 0, 4, 3, 0, 4, 3, 4, 0, 2, 3, 3, 0, 0, 4, 3, 4, 0, 1, 2, 1,
        0, 3, 2, 4, 1, 0, 3, 3, 4, 0, 0, 0, 1, 4, 0, 4, 2, 4, 2, 1, 0, 4,
        3, 0, 1, 3, 2, 4, 1, 1, 0, 4, 2, 4],
       [2, 0, 0, 4, 4, 4, 2, 1, 4, 4, 4, 4, 4, 1, 2, 0, 3, 1, 4, 4, 0, 2,
        3, 2, 4, 2, 2, 2, 1, 1, 1, 0, 3, 0, 2, 0, 4, 1, 0, 2, 0, 3, 0, 3,
        0, 2, 0, 3, 4, 2, 0, 2, 1, 0, 1, 2, 2, 4, 4, 0, 4, 0, 2, 4, 4, 3,
        2, 4, 1, 2, 2, 2, 4, 2, 1, 0, 4, 3, 2, 0, 2, 4, 0, 2, 0, 2, 4, 0,
        4, 3, 4, 0, 2,

In [25]:
y

array([1, 2, 3, 4, 5, 6])

- Multinomial naive bayes 모델 생성

In [26]:
clf = MultinomialNB()
clf.fit(X, y)

MultinomialNB()

In [27]:
print(clf.predict(X[2:3]))

[3]


In [28]:
clf.predict_proba(X[2:3])

array([[8.91509001e-33, 7.35764482e-45, 1.00000000e+00, 1.38756532e-35,
        8.59123447e-40, 3.34215718e-37]])

- prior 변경해보기

In [31]:
clf2 = MultinomialNB(class_prior=[0.1,0.1999,0.0001,0.1,0.1,0.1])
clf2.fit(X, y)

MultinomialNB(class_prior=[0.1, 0.1999, 0.0001, 0.1, 0.1, 0.1])

In [32]:
print(clf2.predict(X[2:3]))

[3]


In [33]:
clf2.predict_proba(X[2:3])

array([[8.91509001e-30, 1.47079320e-41, 1.00000000e+00, 1.38756532e-32,
        8.59123447e-37, 3.34215718e-34]])